name: 'ci'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  svelte-check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
      
      - name: install packages
        run: npm install --package-lock=false 

      - name: run check
        run: npm run check

  cargo-test:
    runs-on: "ubuntu-22.04"
    env:
        RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          version: 1.0
            
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
            workspaces: "src-tauri"

      - name: run tests
        run: cd src-tauri && cargo test

